#ifndef __DUS_HPP_INCLUDED__
#define __DUS_HPP_INCLUDED__

#define PROGRAM_NAME "dus"
#define PROGRAM_VERSION_MAJOR "0"
#define PROGRAM_VERSION_MINOR "0"
#define PROGRAM_VERSION_BUILD "0"
#define PROGRAM_VERSION PROGRAM_VERSION_MAJOR "." PROGRAM_VERSION_MINOR "." PROGRAM_VERSION_BUILD
#define PROGRAM_YEAR "2015"
#define PROGRAM_LICENSE "GPLv3"

#endif //__DUS_HPP_INCLUDED__
