#ifndef __DUS_H_INCLUDED__
#define __DUS_H_INCLUDED__

#define PROGRAM_NAME "dus"
#define PROGRAM_VERSION_MAJOR "0"
#define PROGRAM_VERSION_MINOR "0"
#define PROGRAM_VERSION_BUILD "1"
#define PROGRAM_VERSION PROGRAM_VERSION_MAJOR "." PROGRAM_VERSION_MINOR "." PROGRAM_VERSION_BUILD
#define PROGRAM_LICENSE "GPLv3"

#endif //__DUS_H_INCLUDED__
